version: '3.9'

x-default: &default
  image: node:16.0.0
  working_dir: /app
  volumes:
    - .:/app:cached
    - node_modules:/app/node_modules:delegated
  stdin_open: true
  tty: true

services:
  nextjs_app:
    <<: *default
    container_name: nextjs_app
    command:
      - bash
      - -c
      - |
        yarn
        yarn dev
    ports:
      - 3000:3000

  nextjs_storybook:
    <<: *default
    container_name: nextjs_storybook
    command:
      - bash
      - -c
      - |
        yarn
        yarn storybook
    ports:
      - 6006:6006

volumes:
  node_modules:
